
services:
  graphdb:
    image: neo4j:5.22.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=books/password
    volumes:
      - ./n4jdb/data:/data
      - ./n4jdb/import:/import
      - ./n4jdb/logs:/logs
